// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Issue is the predicate function for issue builders.
type Issue func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)
