FROM golang:1.18-buster as build-go
WORKDIR /go/src/app
COPY . .
RUN cd ./examples/starter && CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-linkmode external -extldflags "-static"' -o main .

FROM alpine:latest
RUN apk add ca-certificates curl
WORKDIR /opt
COPY --from=build-go /go/src/app/examples/starter/main /bin/main
COPY --from=build-go /go/src/app/examples/starter/templates /opt/templates
RUN chmod +x /bin/main
CMD ["/bin/main"]