name: Deploy
on:
  release:
    types: [published, edited]
jobs:
  deploy:
    name: Deploys goliveview-starter on fly.dev
    runs-on: ubuntu-latest
    environment:
      name: fly.dev
      url: https://goliveview-starter.fly.dev
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: |
            secrets set \
            APP_GOOGLE_CLIENT_ID=${{ secrets.APP_GOOGLE_CLIENT_ID }} \
            APP_GOOGLE_SECRET=${{ secrets.APP_GOOGLE_SECRET }} \
            APP_SMTP_HOST=${{ secrets.APP_SMTP_HOST }} \
            APP_SMTP_PORT=${{ secrets.APP_SMTP_PORT }} \
            APP_SMTP_USER=${{ secrets.APP_SMTP_USER }} \
            APP_SMTP_PASS=${{ secrets.APP_SMTP_PASS }} \
            APP_SMTP_ADMIN_EMAIL=${{ secrets.APP_SMTP_ADMIN_EMAIL }} \
            APP_API_MASTER_SECRET=${{ secrets.APP_API_MASTER_SECRET }} || true